name = "f1-worker"
main = "src/worker.js"
compatibility_date = "2024-01-01"
workers_dev = true
compatibility_flags = [ "nodejs_compat" ]

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

# Uncomment if you have a build script.
# [build]
# command = "npm run build"

# Application Enviromnet
[vars]
copyright = 'Blaine Harper'
siteTitle = 'F1-Worker'
url = 'https://f1.blaineharper.com'

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = ""
database_id = ""