function inverse(obj){ 
  var retobj = {}; 
  for(var key in obj){ 
    retobj[obj[key]] = key; 
  } 
  return retobj; 
} 

const nationality = {
  "Afghan": "AF",
  "Albanian": "AL",
  "Algerian": "DZ",
  "Andorran": "AD",
  "Angolan": "AO",
  "Argentine": "AR",
  "Armenian": "AM",
  "Australian": "AU",
  "Austrian": "AT",
  "Azerbaijani": "AZ",
  "Bahamian": "BS",
  "Bahraini": "BH",
  "Bangladeshi": "BD",
  "Barbadian": "BB",
  "Belarusian": "BY",
  "Belgian": "BE",
  "Belizean": "BZ",
  "Beninese": "BJ",
  "Bhutanese": "BT",
  "Bolivian": "BO",
  "Bosnian": "BA",
  "Botswanan": "BW",
  "Brazilian": "BR",
  "British": "GB",
  "Bruneian": "BN",
  "Bulgarian": "BG",
  "Burkinabe": "BF",
  "Burmese": "MM",
  "Burundian": "BI",
  "Cambodian": "KH",
  "Cameroonian": "CM",
  "Canadian": "CA",
  "Cape Verdean": "CV",
  "Central African": "CF",
  "Chadian": "TD",
  "Chilean": "CL",
  "Chinese": "CN",
  "Colombian": "CO",
  "Comoran": "KM",
  "Congolese (Congo-Brazzaville)": "CG",
  "Congolese (Congo-Kinshasa)": "CD",
  "Costa Rican": "CR",
  "Croatian": "HR",
  "Cuban": "CU",
  "Cypriot": "CY",
  "Czech": "CZ",
  "Danish": "DK",
  "Djiboutian": "DJ",
  "Dominican": "DO",
  "Dutch": "NL",
  "East Timorese": "TL",
  "Ecuadorean": "EC",
  "Egyptian": "EG",
  "Salvadoran": "SV",
  "Equatorial Guinean": "GQ",
  "Eritrean": "ER",
  "Estonian": "EE",
  "Ethiopian": "ET",
  "Fijian": "FJ",
  "Finnish": "FI",
  "French": "FR",
  "Gabonese": "GA",
  "Gambian": "GM",
  "Georgian": "GE",
  "German": "DE",
  "Ghanaian": "GH",
  "Greek": "GR",
  "Grenadian": "GD",
  "Guatemalan": "GT",
  "Guinean": "GN",
  "Guinea-Bissauan": "GW",
  "Guyanese": "GY",
  "Haitian": "HT",
  "Honduran": "HN",
  "Hungarian": "HU",
  "Icelander": "IS",
  "Indian": "IN",
  "Indonesian": "ID",
  "Iranian": "IR",
  "Iraqi": "IQ",
  "Irish": "IE",
  "Israeli": "IL",
  "Italian": "IT",
  "Ivorian": "CI",
  "Jamaican": "JM",
  "Japanese": "JP",
  "Jordanian": "JO",
  "Kazakhstani": "KZ",
  "Kenyan": "KE",
  "Kiribati": "KI",
  "North Korean": "KP",
  "South Korean": "KR",
  "Kuwaiti": "KW",
  "Kyrgyzstani": "KG",
  "Lao": "LA",
  "Latvian": "LV",
  "Lebanese": "LB",
  "Lesotho": "LS",
  "Liberian": "LR",
  "Libyan": "LY",
  "Liechtenstein": "LI",
  "Lithuanian": "LT",
  "Luxembourgish": "LU",
  "Macedonian": "MK",
  "Malagasy": "MG",
  "Malawian": "MW",
  "Malaysian": "MY",
  "Maldivian": "MV",
  "Malian": "ML",
  "Maltese": "MT",
  "Marshallese": "MH",
  "Mauritanian": "MR",
  "Mauritian": "MU",
  "Mexican": "MX",
  "Micronesian": "FM",
  "Moldovan": "MD",
  "Monacan": "MC",
  "Monegasque": "MC",
  "Mongolian": "MN",
  "Montenegrin": "ME",
  "Moroccan": "MA",
  "Mozambican": "MZ",
  "Namibian": "NA",
  "Nauruan": "NR",
  "Nepalese": "NP",
  "New Zealander": "NZ",
  "Nicaraguan": "NI",
  "Nigerien": "NE",
  "Nigerian": "NG",
  "Norwegian": "NO",
  "Omani": "OM",
  "Pakistani": "PK",
  "Palauan": "PW",
  "Palestinian": "PS",
  "Panamanian": "PA",
  "Papua New Guinean": "PG",
  "Paraguayan": "PY",
  "Peruvian": "PE",
  "Philippine": "PH",
  "Polish": "PL",
  "Portuguese": "PT",
  "Qatari": "QA",
  "Romanian": "RO",
  "Russian": "RU",
  "Rwandan": "RW",
  "Saint Lucian": "LC",
  "Samoan": "WS",
  "San Marinese": "SM",
  "Sao Tomean": "ST",
  "Saudi": "SA",
  "Senegalese": "SN",
  "Serbian": "RS",
  "Seychellois": "SC",
  "Sierra Leonean": "SL",
  "Singaporean": "SG",
  "Slovak": "SK",
  "Slovenian": "SI",
  "Solomon Islander": "SB",
  "Somali": "SO",
  "South African": "ZA",
  "South Sudanese": "SS",
  "Spanish": "ES",
  "Sri Lankan": "LK",
  "Sudanese": "SD",
  "Surinamer": "SR",
  "Swazi": "SZ",
  "Swedish": "SE",
  "Swiss": "CH",
  "Syrian": "SY",
  "Taiwanese": "TW",
  "Tajikistani": "TJ",
  "Tanzanian": "TZ",
  "Thai": "TH",
  "Togolese": "TG",
  "Tongan": "TO",
  "Trinidadian": "TT",
  "Tunisian": "TN",
  "Turkish": "TR",
  "Turkmen": "TM",
  "Tuvaluan": "TV",
  "Ugandan": "UG",
  "Ukrainian": "UA",
  "Emirati": "AE",
  "Uruguayan": "UY",
  "Uzbekistani": "UZ",
  "Vanuatuan": "VU",
  "Venezuelan": "VE",
  "Vietnamese": "VN",
  "Yemeni": "YE",
  "Zambian": "ZM",
  "Zimbabwean": "ZW"
}

export function nationToIso2(nation) {
  return nationality[nation] || 'US'
}

export function iso2ToNation(iso2) {
  const invNationality = inverse(nationality)
  return invNationality[iso2] || 'USA'
}

export function iso3To2(iso3Code) {
  // Dictionary mapping ISO 3166-1 alpha-3 codes to alpha-2 codes
  const isoMapping = {
      "AFG": "AF", "ALB": "AL", "DZA": "DZ", "ASM": "AS", "AND": "AD",
      "AGO": "AO", "AIA": "AI", "ATA": "AQ", "ATG": "AG", "ARG": "AR",
      "ARM": "AM", "ABW": "AW", "AUS": "AU", "AUT": "AT", "AZE": "AZ",
      "BHS": "BS", "BHR": "BH", "BGD": "BD", "BRB": "BB", "BLR": "BY",
      "BEL": "BE", "BLZ": "BZ", "BEN": "BJ", "BMU": "BM", "BTN": "BT",
      "BOL": "BO", "BIH": "BA", "BWA": "BW", "BRA": "BR", "IOT": "IO",
      "BRN": "BN", "BGR": "BG", "BFA": "BF", "BDI": "BI", "CPV": "CV",
      "KHM": "KH", "CMR": "CM", "CAN": "CA", "CYM": "KY", "CAF": "CF",
      "TCD": "TD", "CHL": "CL", "CHN": "CN", "COL": "CO", "COM": "KM",
      "COG": "CG", "COD": "CD", "COK": "CK", "CRI": "CR", "HRV": "HR",
      "CUB": "CU", "CUW": "CW", "CYP": "CY", "CZE": "CZ", "DNK": "DK", "DEN": "DK",
      "DJI": "DJ", "DMA": "DM", "DOM": "DO", "ECU": "EC", "EGY": "EG",
      "SLV": "SV", "GNQ": "GQ", "ERI": "ER", "EST": "EE", "SWZ": "SZ",
      "ETH": "ET", "FLK": "FK", "FRO": "FO", "FJI": "FJ", "FIN": "FI",
      "FRA": "FR", "GUF": "GF", "PYF": "PF", "ATF": "TF", "GAB": "GA",
      "GMB": "GM", "GEO": "GE", "DEU": "DE", "GER": "DE", "GHA": "GH", "GIB": "GI",
      "GRC": "GR", "GRL": "GL", "GRD": "GD", "GLP": "GP", "GUM": "GU",
      "GTM": "GT", "GGY": "GG", "GIN": "GN", "GNB": "GW", "GUY": "GY",
      "HTI": "HT", "HND": "HN", "HKG": "HK", "HUN": "HU", "ISL": "IS",
      "IND": "IN", "IDN": "ID", "IRN": "IR", "IRQ": "IQ", "IRL": "IE",
      "IMN": "IM", "ISR": "IL", "ITA": "IT", "JAM": "JM", "JPN": "JP",
      "JEY": "JE", "JOR": "JO", "KAZ": "KZ", "KEN": "KE", "KIR": "KI",
      "PRK": "KP", "KOR": "KR", "KWT": "KW", "KGZ": "KG", "LAO": "LA",
      "LVA": "LV", "LBN": "LB", "LSO": "LS", "LBR": "LR", "LBY": "LY",
      "LIE": "LI", "LTU": "LT", "LUX": "LU", "MAC": "MO", "MDG": "MG",
      "MWI": "MW", "MYS": "MY", "MDV": "MV", "MLI": "ML", "MLT": "MT",
      "MHL": "MH", "MTQ": "MQ", "MRT": "MR", "MUS": "MU", "MYT": "YT",
      "MEX": "MX", "FSM": "FM", "MDA": "MD", "MCO": "MC", "MON": "MC", "MNG": "MN",
      "MNE": "ME", "MSR": "MS", "MAR": "MA", "MOZ": "MZ", "MMR": "MM",
      "NAM": "NA", "NRU": "NR", "NPL": "NP", "NLD": "NL", "NED": "NL", "NCL": "NC",
      "NZL": "NZ", "NIC": "NI", "NER": "NE", "NGA": "NG", "NIU": "NU",
      "NFK": "NF", "MNP": "MP", "NOR": "NO", "OMN": "OM", "PAK": "PK",
      "PLW": "PW", "PAN": "PA", "PNG": "PG", "PRY": "PY", "PER": "PE",
      "PHL": "PH", "PCN": "PN", "POL": "PL", "PRT": "PT", "PRI": "PR",
      "QAT": "QA", "MKD": "MK", "ROU": "RO", "RUS": "RU", "RWA": "RW",
      "REU": "RE", "BLM": "BL", "SHN": "SH", "KNA": "KN", "LCA": "LC",
      "MAF": "MF", "SPM": "PM", "VCT": "VC", "WSM": "WS", "SMR": "SM",
      "STP": "ST", "SAU": "SA", "SEN": "SN", "SRB": "RS", "SYC": "SC",
      "SLE": "SL", "SGP": "SG", "SXM": "SX", "SVK": "SK", "SVN": "SI",
      "SLB": "SB", "SOM": "SO", "ZAF": "ZA", "SGS": "GS", "SSD": "SS",
      "ESP": "ES", "LKA": "LK", "SDN": "SD", "SUR": "SR", "SJM": "SJ",
      "SWE": "SE", "CHE": "CH", "SYR": "SY", "TWN": "TW", "TJK": "TJ",
      "TZA": "TZ", "THA": "TH", "TLS": "TL", "TGO": "TG", "TKL": "TK",
      "TON": "TO", "TTO": "TT", "TUN": "TN", "TUR": "TR", "TKM": "TM",
      "TCA": "TC", "TUV": "TV", "UGA": "UG", "UKR": "UA", "ARE": "AE",
      "GBR": "GB", "USA": "US", "URY": "UY", "UZB": "UZ", "VUT": "VU",
      "VEN": "VE", "VNM": "VN", "VGB": "VG", "VIR": "VI", "WLF": "WF",
      "ESH": "EH", "YEM": "YE", "ZMB": "ZM", "ZWE": "ZW"
  };

  return isoMapping[iso3Code.toUpperCase() || ''] || null;
}