UPDATE driver_standings SET teamId = 1 WHERE driverId = 830;  -- Max Verstappen
UPDATE driver_standings SET teamId = 2 WHERE driverId = 1;  -- Lewis Hamilton
UPDATE driver_standings SET teamId = 4 WHERE driverId = 846;  -- Lando Norris
UPDATE driver_standings SET teamId = 3 WHERE driverId = 844;  -- Charles LeClerc
UPDATE driver_standings SET teamId = 3 WHERE driverId = 832;  -- Carlos Sainz
UPDATE driver_standings SET teamId = 1 WHERE driverId = 815;  -- Sergio Perez
UPDATE driver_standings SET teamId = 4 WHERE driverId = 857;  -- Oscar Piastri
UPDATE driver_standings SET teamId = 2 WHERE driverId = 847;  -- George RUSSELL
UPDATE driver_standings SET teamId = 9 WHERE driverId = 4;  -- Fernando ALONSO
UPDATE driver_standings SET teamId = 11 WHERE driverId = 852;  -- Yuki TSUNODA
UPDATE driver_standings SET teamId = 9 WHERE driverId = 840;  -- Lance STROLL
UPDATE driver_standings SET teamId = 11 WHERE driverId = 817;  -- Daniel RICCIARDO
UPDATE driver_standings SET teamId = 24 WHERE driverId = 807;  -- Nico HÜLKENBERG
UPDATE driver_standings SET teamId = 3 WHERE driverId = 860;  -- Oliver BEARMAN
UPDATE driver_standings SET teamId = 6 WHERE driverId = 842;  -- Pierre GASLY
UPDATE driver_standings SET teamId = 6 WHERE driverId = 839;  -- Esteban OCON
UPDATE driver_standings SET teamId = 5 WHERE driverId = 848;  -- Alexander ALBON
UPDATE driver_standings SET teamId = 24 WHERE driverId = 825;  -- Kevin MAGNUSSEN
UPDATE driver_standings SET teamId = 14 WHERE driverId = 855;  -- Guanyu ZHOU
UPDATE driver_standings SET teamId = 14 WHERE driverId = 822;  -- Valtteri BOTTAS
UPDATE driver_standings SET teamId = 5 WHERE driverId = 858;  -- Logan SARGEANT
UPDATE driver_standings SET teamId = 11 WHERE driverId = 856;  -- Nyck DE VRIES
UPDATE driver_standings SET teamId = 11 WHERE driverId = 859;  -- Liam LAWSON
UPDATE driver_standings SET teamId = 9 WHERE driverId = 20;  -- Sebastian Vettel
UPDATE driver_standings SET teamId = 24 WHERE driverId = 30;  -- Mick Schumacher
UPDATE driver_standings SET teamId = 5 WHERE driverId = 849;  -- Nicholas Latifi
UPDATE driver_standings SET teamId = 8 WHERE driverId = 8;  -- Kimi RÄIKKÖNEN
UPDATE driver_standings SET teamId = 24 WHERE driverId = 853;  -- Nikita Mazepan